# Generated by Django 4.2.20 on 2025-03-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Food & Dining', 'Food & Dining'), ('Shopping', 'Shopping'), ('Transportation', 'Transportation'), ('Entertainment', 'Entertainment'), ('Bills & Utilities', 'Bills & Utilities'), ('Healthcare', 'Healthcare'), ('Travel', 'Travel'), ('Other', 'Other')], max_length=50)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
