# Generated by Django 4.2.20 on 2025-03-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food & Dining', 'Food & Dining'), ('Transportation', 'Transportation'), ('Utilities', 'Utilities'), ('Housing', 'Housing'), ('Entertainment', 'Entertainment'), ('Healthcare', 'Healthcare'), ('Shopping', 'Shopping'), ('Personal Care', 'Personal Care'), ('Education', 'Education'), ('Travel', 'Travel'), ('Other', 'Other')], max_length=50),
        ),
    ]
